kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-pamela
spec:
  rules:
    - host: pamela.%DOMAIN%
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pamela
                port:
                  number: 3001
